/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\\public\\models\\t_shirt_b.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/t_shirt_b.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.T_Shirt_Male.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/t_shirt_b.glb')
